openapi: '3.0.0'
info:
  title: 'Badge API'
  version: '1.0.0'
tags:
  - name: 'Badge'
paths:
  /badge/getAll:
    get:
      tags:
        - 'Badge'
      summary: Get all badges
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /badge/getById/{id}:
    get:
      tags:
        - 'Badge'
      summary: Get badge by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /badge/update/{id}:
    patch:
      tags:
        - 'Badge'
      summary: Update badge
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                points:
                  type: integer
                display_img:
                  type: string
      responses:
        '200':
          description: Badge updated
        '400':
          description: Bad request
  /badge/deleteById/{id}:
    delete:
      tags:
        - 'Badge'
      summary: Delete badge by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Badge deleted
        '400':
          description: Bad request
