openapi: '3.0.0'
info:
  title: 'Info API'
  version: '1.0.0'
tags:
  - name: 'Info'
paths:
  /info/create:
    post:
      tags:
        - 'Info'
      summary: Create a new info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                icon:
                  type: string
                content:
                  type: string
                date_start:
                  type: string
                date_end:
                  type: string
      responses:
        '201':
          description: Info created
        '400':
          description: Bad request
  /info/getAll:
    get:
      tags:
        - 'Info'
      summary: Get all infos
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /info/getById/{id}:
    get:
      tags:
        - 'Info'
      summary: Get info by id
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /info/update/{id}:
    patch:
      tags:
        - 'Info'
      summary: Update info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                icon:
                  type: string
                content:
                  type: string
                date_start:
                  type: string
                date_end:
                  type: string
      responses:
        '200':
          description: Info updated
        '400':
          description: Bad request
  /info/deleteById/{id}:
    delete:
      tags:
        - 'Info'
      summary: Delete info by id
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Info deleted
        '400':
          description: Bad request
