openapi: '3.0.0'
info:
  title: 'Instrument API'
  version: '1.0.0'
tags:
  - name: 'Instrument'
paths:
  /instrument/create:
    post:
      tags:
        - 'Instrument'
      summary: Create a new instrument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id_category:
                  type: integer
      responses:
        '201':
          description: Instrument created
        '400':
          description: Bad request
  /instrument/getAll:
    get:
      tags:
        - 'Instrument'
      summary: Get all instruments
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /instrument/getById/{id}:
    get:
      tags:
        - 'Instrument'
      summary: Get instrument by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /instrument/update/{id}:
    patch:
      tags:
        - 'Instrument'
      summary: Update instrument
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id_category:
                  type: integer
      responses:
        '200':
          description: Instrument updated
        '400':
          description: Bad request
  /instrument/deleteById/{id}:
    delete:
      tags:
        - 'Instrument'
      summary: Delete instrument by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Instrument deleted
        '400':
          description: Bad request
