openapi: '3.0.0'
info:
  title: 'Role API'
  version: '1.0.0'
tags:
  - name: 'Role'
paths:
  /role/create:
    post:
      tags:
        - 'Role'
      summary: Create a new role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Role created
        '400':
          description: Bad request
  /role/getAll:
    get:
      tags:
        - 'Role'
      summary: Get all roles
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /role/getById/{id}:
    get:
      tags:
        - 'Role'
      summary: Get role by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /role/update/{id}:
    patch:
      tags:
        - 'Role'
      summary: Update role
       parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      responses:
        '200':
          description: Role updated
        '400':
          description: Bad request
  /role/deleteById/{id}:
    delete:
      tags:
        - 'Role'
      summary: Delete role by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Role deleted
        '400':
          description: Bad request
