openapi: '3.0.0'
info:
  title: 'Video API'
  version: '1.0.0'
tags:
  - name: 'Video'
paths:
  /video/create:
    post:
      tags:
        - 'Video'
      summary: Create a new video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                link:
                  type: string
      responses:
        '201':
          description: Video created
        '400':
          description: Bad request
  /video/getAll:
    get:
      tags:
        - 'Video'
      summary: Get all videos
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /video/getById/{id}:
    get:
      tags:
        - 'Video'
      summary: Get video by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /video/update/{id}:
    patch:
      tags:
        - 'Video'
      summary: Update video
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                link:
                  type: string
      responses:
        '200':
          description: Video updated
        '400':
          description: Bad request
  /video/deleteById/{id}:
    delete:
      tags:
        - 'Video'
      summary: Delete video by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Video deleted
        '400':
          description: Bad request
