name: CI

on:
  push:
    branches:
      - main # nom de la branche sur laquelle ce pipeline écoute le push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code in runner
        uses: actions/checkout@v3
      
      - name: Push to Server
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          sshpass -p ${{ secrets.GIT_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.USER }}@${{ secrets.SERVER_HOST }} 'cd ${{ secrets.DESTINATION_PATH }} && git pull'

      - name: Build
        run: 
          cd /home/hetic/backend-upper
          echo $PWD
          npm run start