name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code in runner
        uses: actions/checkout@v3

      - name: Remove local files and images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.GIT_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Cleaning all files"
            GLOBALIGNORE=".env server-setup.sh"
            find ${{ secrets.DESTINATION_PATH }} -type f -not -name $GLOBALIGNORE -exec rm -f {} +
            pm2 stop my-app
            echo "Cleaning complete"

      - name: Update Apt
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy files to server
        run: |
          echo "Copying files to server"
          sshpass -p ${{ secrets.GIT_PASSWORD }} scp -o StrictHostKeyChecking=no -r -P ${{ secrets.SERVER_PORT }} $GITHUB_WORKSPACE/* ${{ secrets.USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DESTINATION_PATH }}
          echo "File copy complete"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.4.0

      - name: Install dependencies and run scripts on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.GIT_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export NVM_DIR="/home/upper/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20.4.0
            cd ${{ secrets.PROJECT_PATH }}
            npm ci
            npm i @prisma/client
            npm i -g pm2
            npx prisma generate
            npx prisma migrate dev --name init
            bash server-setup.sh